name: First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: list and read file
          run: |
            echo "First Github action job"
            ls -ltr
            cat README.md

        - name: generate ASCII Artwork
          run: cowsay -f dragon "Run for cover" >> dragon.txt

        # - name: List Files
        #   run: ls 
        
        # - name: Read Files
        #   run: cat README.md