name: First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: Message
          run: echo "First Github action job"

        - name: List Files
          run: ls 
        
        - name: Read Files
          run: cat README.md