name: matrix Workflow
on: 
  push:
  workflow_dispatch:

jobs:
    deploy:
      strategy:
        fail-fast: false
        matrix:
          os: [ ubuntu-latest, ubuntu-20.04, windows-latest ]
          images: [ hello-world, alpine ]
          exclude:
            - images: alpine
              os: windows-latest
      runs-on: ${{ matrix.os }}
      steps:
      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}