name: matrix Workflow
on: 
  push:
  workflow_dispatch:

jobs:
    deploy:
      strategy:
        matrix:
          os: [ ubuntu-latest, ubuntu-20.04, windows-latest ]
          images: [ hellow-world, alpine ]
      runs-on: ${{ matrix.os }}
      steps:
      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}